R/annotation.r
R/app-countQC.R
R/ngsio.r
R/plots-reports.R
R/rawData.R
README.md

SummarizedExperiment based rawData for countQC

Summarized experiment

---

DESCRIPTION
R/app-mapping.r
inst/extdata/EZ_PARAM_DEFAULTS.txt

Per-sample 2-pass mapping for STAR

version 1.0.10

---

DESCRIPTION
R/app-RnaBamStats.R
R/app-featureCounts.R
R/bamio.r
R/featurePlots.r
R/gff.r
R/system.R
inst/templates/FastQC.Rmd
inst/templates/RNABamStats.R

With 8 cores, 17 elapsed minutes for a 1.8G bam

Fast implementation of RnaBamStats

---

DESCRIPTION
R/app-countQC.R
R/app-deseq2TwoGroups.R
R/app-edgerTwoGroups.R
R/ngsio.r
R/twoGroups.R
inst/templates/twoGroups.Rmd
man/loadCountDatasetSE.Rd

countQC and twoGroups export deResult with se only.

version 1.0.14

---

DESCRIPTION
R/app-RnaBamStats.R
R/util.r
README.md
inst/templates/RNABamStats.R
inst/templates/RNABamStats.Rmd
man/getDupRateFromBam.Rd

RNABamStats with duplication rate quality control from dupRadar

version 1.1.0

---

R/app-featureCounts.R
R/app-scCount.R
R/app-scMapping.R
R/app-scater.R
script/debug-scRNA.R

Mapping and counting in one step

EzAppsSCCounts

---

DESCRIPTION
R/go-analysis.R
R/go-reports.R
README.md
inst/templates/twoGroups.Rmd

Add links for dowloading GO result files.
Always output goseq results file, even not significant.

Two group GO

---

DESCRIPTION
R/ngsPlots.r
README.md
inst/templates/CountQC.R
inst/templates/CountQC.Rmd
inst/templates/FastQC.Rmd

interactive counts statistics and mds plot

interactive for CountQC

---

R/01classes.R
R/annotation.r
R/app-AtacENCODE.R
R/util.r
inst/extdata/EZ_GLOBAL_VARIABLES.txt
man/getBlacklistedRegions.Rd
script/debug-atacENCODE.R

App based on ENCODE ATAC-seq pipeline https://github.com/kundajelab/atac_dnase_pipelines

Add EzAppAtacENCODE

---

R/bamUtils.R
man/dupBam.Rd
man/ezSortIndexBam.Rd
script/debug-atacENCODE.R

Preprocess ATAC-seq bam

---

DESCRIPTION
R/app-macs2.R
R/bamUtils.R
R/util.r
script/debug-atacENCODE.R

ATAC-seq pipeline

---

R/Picard.R
R/annotation.r
R/app-SCCountQC.R
R/app-scMapping.R
R/fastqIO.R
R/ngsio.r
R/util.r
README.md
inst/templates/SCCountQC.R
inst/templates/SCCountQC.Rmd
man/CollectAlignmentSummaryMetrics.Rd
man/loadSCCountDataset.Rd

alignment metrics and rnaseq metrics

Single cell: picard metrics

---

R/app-SCCountQC.R
R/app-featureCounts.R
R/gff.r
R/ngsio.r
inst/templates/SCCountQC.R
man/trimGRanges.Rd

Fix the subsettiing SingleCellExperiment with rownames.
coersion with from SummarizedExperiment to SingleCellExperiment is problematic.

Single cell

---

DESCRIPTION
R/app-scCount.R
R/app-scMapping.R
R/bamUtils.R
R/bamio.r
R/fastqIO.R
script/debug-scRNA.R

EzAppSCCounts

---

R/app-fastqscreen.R
inst/templates/FastqScreen.R
inst/templates/FastqScreen.Rmd

plotly based barplot. works better for lots of samples from single cell

fastqscreen

---

inst/templates/CountQC.Rmd
inst/templates/FastqScreen.Rmd
inst/templates/twoGroups.Rmd

Fix names and add margins in fastqscreen

rmd report

---

R/app-cellRanger.R
inst/extdata/EZ_GLOBAL_VARIABLES.txt
inst/templates/SCCountQC.Rmd
script/debug-CellRanger.R

CellRanger use refBuild parameter

---

R/app-SCRNAVelocity.R
R/plots.R
inst/templates/SCRNAVelocity.R
inst/templates/SCRNAVelocity.Rmd

Single cell: RNA velocity as an App

EzAppSCRNAVelocity

---

R/app-SCReport.R
R/app-SCSeurat.R
R/app-fastQC.R
R/app-fastqscreen.R
R/fastqIO.R

when > 1e9 reads in all samples

fastqc and fastqscreen: subsample

---

R/DADA2associatedFunctions.R
R/app-PhyloseqAnalysis.R
R/mothurPhyloseqAssociatedFunctions.R
inst/templates/PhyloseqReport.Rmd

merging metagenomics branch, complete report v.1

Metagenomics apps

---

R/app-DADA2Step1Sample.R
R/app-MothurStep1Sample.R
R/mothurPhyloseqAssociatedFunctions.R
inst/templates/PhyloseqReport.Rmd

main commit consolidating mothur apps

main commit consolidating mothur apps

---

R/SGSeqAssociatedFunctions.R
R/app-SGseq.R

SGSeq app 1st step  main commit

SGSeq app 1st step  main commit

---

R/app-SGseq.R

added two output files

---

R/app-MothurStep1Sample.R
R/app-PhyloseqAnalysis.R
R/mothurAssociatedFunctions.R
R/mothurPhyloseqAssociatedFunctions.R
inst/templates/PhyloseqReport.Rmd
inst/templates/PhyloseqReportNoGroup.Rmd

added QC and chimera plots; improved heatmap

added QC and chimera plots; improved heatmap

---

R/app-cellRanger.R
R/app-cellRangerATAC.R
R/app-spaceRanger.R
inst/extdata/EZ_GLOBAL_VARIABLES.txt

add SpaceRanger app

---

R/app-trim.R

added window trimming options to fastpApp

---

R/00defaults.R
R/app-countQC.R
R/ngsio.r
R/rawData.R
R/util.r
R/zzz.R
inst/templates/CountQC.Rmd
inst/templates/CountQC_goClusterTable.Rmd
script/archived-scripts/CountQC_archived.Rmd

1. faster implementation.
2. use SummarizedExperiment object as much as possible; remove unnecessary intermediate variables.
3. More isolated tabs.
4. Save the final `rawData_final.rds` for easy regeneration of the figures.

Refactor CountQC

---

R/app-kallisto.R

update kallistor to use fastp

---

R/app-fastQC_10x.R
R/app-fastqscreen_10x.R

fastQC and fastqscreen for 10x: calculate Read count in fly

Single cell fastQC and fastqscreen

---

.gitignore
DESCRIPTION
R/02references.R
R/annotation.r
R/gff.r
README.md

1. Much more debug-friendly initialisation of `EzRef`, `buildRefDir`, `buildIgvGenome`.
2. More concise and robust code
3. Adapter tidyverse style instead of data.table

refactor reference build code

---

inst/templates/ScSeurat.Rmd

Remove cell level heatmap

---

R/app-NfCoreAtacSeq.R
inst/templates/DiffPeak.Rmd

Hello @opitzl, plots are rendered properly, but for some reasons tables are not displayed via `ezInteractiveTableRmd()`... Any suggestions are more than welcome! Thanks!

adjust plot rendering
